models:
  gpt-4.1-mini:
    provider: openai
    model_name: gpt-4.1-mini
    max_tokens: 8192
    temperature: 0.0
    max_workers: 64
    max_retries: 3
    timeout: 60
  
  gpt-5.2:
    provider: openai
    model_name: gpt-5.2
    max_completion_tokens: 32768
    temperature: 1.0
    max_workers: 128
    presence_penalty: 0.0
    frequency_penalty: 0.0
    max_retries: 5
    max_retries_api: 5
    timeout: 500
    reasoning_effort: medium
  
  gemini-3-pro-preview:
    provider: openai
    organization: google
    model_name: gemini-3-pro-preview
    max_tokens: 32768
    temperature: 1.0
    max_workers: 32
    base_url: https://generativelanguage.googleapis.com/v1beta/openai/
    timeout: 500
    max_retries: 5

  gemini-3-pro:
    provider: openai
    model_name: gemini-3-pro
    base_url: http://139.224.231.89:8765/v1
    max_completion_tokens: 32768
    temperature: 1.0
    max_workers: 128
    max_retries: 5
    max_retries_api: 5
    timeout: 500

  claude-sonnet-4-5:
    provider: anthropic
    model_name: claude-sonnet-4-5
    max_tokens: 32768
    budget_tokens: 30000
    thinking: true
    temperature: 1.0
    max_workers: 32
    timeout: 300

  glm-4.6v:
    provider: openai
    organization: openrouter
    model_name: glm-4.6v
    max_tokens: 32768
    temperature: 0.0
    max_workers: 32
    base_url: https://openrouter.ai/api/v1
    timeout: 300
    max_retries: 5
    max_retries_api: 5

  qwen3-vl-235b-a22b-thinking:
    provider: openai
    organization: openrouter
    model_name: qwen/qwen3-vl-235b-a22b-thinking
    max_tokens: 32768
    temperature: 0.0
    max_workers: 32
    base_url: https://openrouter.ai/api/v1
    timeout: 300
    max_retries: 5
    max_retries_api: 5

  # vllm
  qwen3-vl-2b-instruct:
    provider: openai
    organization: self-hosted
    model_name: qwen3-vl-2b-instruct
    base_url: http://localhost:9999/v1
    max_completion_tokens: 8192
    temperature: 0.0
    max_workers: 16
    max_retries: 3
    timeout: 600